In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, date

In [3]:
def unir_archivos_st(auctions,events,target):

    auctions.columns = ['ref_hash','s_h20-4','s_h4-12','s_t_min','s_t_prom','s_t_max',
                        's_source_id','s_h12-20','s_#subastas']
    target.columns = ['ref_hash','segundos']
    auctions['subasta'] = 1
    
    todo = pd.merge(auctions,target,on='ref_hash',how='outer')
    todo = pd.merge(todo,events,on='ref_hash',how='left')
    
    t_max = 259200
    vacios = {'s_t_min':t_max, 's_t_prom':t_max, 's_t_max':t_max,
              'e_t_prom': t_max, 'segundos':t_max}
    todo = todo.fillna(vacios).fillna(0)
    return todo

In [4]:
auctions = pd.read_csv('auctions_train2_1820.csv')
events = pd.read_csv('events_train2_1820.csv')
target = pd.read_csv('auctions_test_1820.csv')
todo = unir_archivos_st(auctions,events,target)
todo.to_csv('entrenar2_st_1820.csv', index=False)
todo.head()

,ref_hash,s_h20-4,s_h4-12,s_t_min,s_t_prom,s_t_max,s_source_id,s_h12-20,s_#subastas,subasta,segundos,e_t_prom,e_kind,e_app_id,e_eventoId
0,41863526108385,17.0,17.0,157228.0,185636.171429,189019.0,0.122122,1.0,35.0,1.0,259200.0,140062.647727,0.126640,0.211054,11.105743
1,135153013040192,0.0,8.0,187854.0,188381.875000,188652.0,0.508547,0.0,8.0,1.0,259200.0,259200.000000,0.000000,0.000000,0.000000
2,161514654074162,6.0,0.0,10366.0,10425.333333,10489.0,0.249773,0.0,6.0,1.0,259200.0,147937.250000,0.057634,0.087007,0.470373
3,181891380775191,1.0,0.0,256765.0,256765.000000,256765.0,0.508547,0.0,1.0,1.0,259200.0,259200.000000,0.000000,0.000000,0.000000
4,186034136943920,5.0,0.0,60166.0,160935.142857,257677.0,0.508547,2.0,7.0,1.0,88.0,60125.769231,0.148482,0.253877,1.923081

In [6]:
auctions = pd.read_csv('auctions_train2_1921.csv')
events = pd.read_csv('events_train2_1921.csv')
target = pd.read_csv('auctions_test_1921.csv')
todo = unir_archivos_st(auctions,events,target)
todo.to_csv('entrenar2_st_1921.csv', index=False)
todo.head()

,ref_hash,s_h20-4,s_h4-12,s_t_min,s_t_prom,s_t_max,s_source_id,s_h12-20,s_#subastas,subasta,segundos,e_t_prom,e_kind,e_app_id,e_eventoId
0,41863526108385,17.0,17.0,70828.0,99236.171429,102619.0,0.122257,1.0,35.0,1.0,259200.0,88923.736111,0.147983,0.261183,10.618843
1,135153013040192,0.0,8.0,101454.0,101981.875000,102252.0,0.507354,0.0,8.0,1.0,259200.0,259200.000000,0.000000,0.000000,0.000000
2,181891380775191,1.0,0.0,170365.0,170365.000000,170365.0,0.507354,0.0,1.0,1.0,259200.0,259200.000000,0.000000,0.000000,0.000000
3,186034136943920,10.0,5.0,98271.0,174949.062500,257356.0,0.507354,1.0,16.0,1.0,17475.0,259200.000000,0.000000,0.000000,0.000000
4,295841792051458,1.0,0.0,173232.0,173232.000000,173232.0,0.507354,0.0,1.0,1.0,259200.0,259200.000000,0.000000,0.000000,0.000000

In [7]:
auctions = pd.read_csv('auctions_train2_2022.csv')
events = pd.read_csv('events_train2_2022.csv')
target = pd.read_csv('auctions_test_2022.csv')
todo = unir_archivos_st(auctions,events,target)
todo.to_csv('entrenar2_st_2022.csv', index=False)
todo.head()

,ref_hash,s_h20-4,s_h4-12,s_t_min,s_t_prom,s_t_max,s_source_id,s_h12-20,s_#subastas,subasta,segundos,e_t_prom,e_kind,e_app_id,e_eventoId
0,41863526108385,17.0,17.0,10346.0,13671.705882,16219.0,0.124705,0.0,34.0,1.0,259200.0,31455.568627,0.146337,0.26299,7.43873
1,135153013040192,0.0,8.0,15054.0,15581.875000,15852.0,0.516090,0.0,8.0,1.0,259200.0,259200.000000,0.000000,0.00000,0.00000
2,181891380775191,1.0,0.0,83965.0,83965.000000,83965.0,0.516090,0.0,1.0,1.0,259200.0,259200.000000,0.000000,0.00000,0.00000
3,186034136943920,14.0,30.0,11871.0,168457.019608,255971.0,0.516090,7.0,51.0,1.0,3832.0,237222.571429,0.133386,0.26299,3.72259
4,295841792051458,1.0,0.0,86832.0,86832.000000,86832.0,0.516090,0.0,1.0,1.0,259200.0,259200.000000,0.000000,0.00000,0.00000

In [8]:
auctions = pd.read_csv('auctions_train2_2123.csv')
events = pd.read_csv('events_train2_2123.csv')
target = pd.read_csv('auctions_test_2123.csv')
todo = unir_archivos_st(auctions,events,target)
todo.to_csv('entrenar2_st_2123.csv', index=False)
todo.head()

,ref_hash,s_h20-4,s_h4-12,s_t_min,s_t_prom,s_t_max,s_source_id,s_h12-20,s_#subastas,subasta,segundos,e_t_prom,e_kind,e_app_id,e_eventoId
0,40621409780134,0.0,0.0,226857.0,226857.000000,226857.0,0.229348,1.0,1.0,1.0,259200.0,122304.666667,0.008657,0.005934,0.077695
1,168103949904656,1.0,0.0,173044.0,173044.000000,173044.0,0.152259,0.0,1.0,1.0,259200.0,87199.100000,0.087588,0.034847,0.896247
2,186034136943920,10.0,32.0,88.0,122681.220339,222609.0,0.522137,17.0,59.0,1.0,259200.0,172658.000000,0.123917,0.264696,5.062785
3,295841792051458,1.0,0.0,432.0,432.000000,432.0,0.522137,0.0,1.0,1.0,259200.0,259200.000000,0.000000,0.000000,0.000000
4,345999128501141,24.0,0.0,164703.0,248794.166667,256365.0,0.509938,0.0,24.0,1.0,250362.0,259200.000000,0.000000,0.000000,0.000000

In [9]:
auctions = pd.read_csv('auctions_train2_2426.csv')
events = pd.read_csv('events_train2_2426.csv')
target = pd.read_csv('ids.csv')
todo = unir_archivos_st(auctions,events,target)
todo.to_csv('predecir2_st_2426.csv', index=False)
todo.head()

,ref_hash,s_h20-4,s_h4-12,s_t_min,s_t_prom,s_t_max,s_source_id,s_h12-20,s_#subastas,subasta,segundos,e_t_prom,e_kind,e_app_id,e_eventoId
0,69039685746313,0.0,4.0,126258.0,126455.500000,126704.0,0.027635,0.0,4.0,1.0,259200.0,229631.8125,0.061761,0.029999,0.984140
1,345999128501141,2.0,0.0,250362.0,250382.000000,250402.0,0.005048,0.0,2.0,1.0,259200.0,259200.0000,0.000000,0.000000,0.000000
2,360710529886978,5.0,0.0,46687.0,162802.071429,256671.0,0.414065,37.0,42.0,1.0,259200.0,259200.0000,0.000000,0.000000,0.000000
3,365882020742330,1.0,1.0,96627.0,143426.000000,190225.0,0.022213,0.0,2.0,1.0,259200.0,187550.0000,0.043729,0.016905,0.130703
4,416301579449694,28.0,2.0,12569.0,95799.048387,182084.0,0.344891,32.0,62.0,1.0,259200.0,259200.0000,0.000000,0.000000,0.000000

In [6]:
def unir_archivos_sc(events,clicks,installs,target):

    todo = pd.merge(events,clicks,on='ref_hash',how='outer')
    todo = pd.merge(todo,installs,on='ref_hash',how='outer')
    todo = pd.merge(todo,target,on='ref_hash',how='outer')
    
    t_max = 259200
    vacios = {'e_t_prom': t_max, 'c_t_prom':t_max, 'c_timeToClick':t_max,
              'i_t_min':t_max, 'i_t_prom':t_max, 'i_t_max':t_max, 'segundos':t_max}
    todo = todo.fillna(vacios).fillna(0)
    del todo['i_attributed']
    return todo

In [50]:
events = pd.read_csv('events_train_1820.csv')
clicks = pd.read_csv('clicks_train_1820.csv')
installs = pd.read_csv('installs_train_1820.csv')
target = pd.read_csv('installs_test_1820.csv')
todo = unir_archivos_sc(events,clicks,installs,target)
todo.to_csv('entrenar_sc_1820.csv', index=False)
todo.head()

,ref_hash,e_kind,e_app_id,e_event_id,e_#wifi,e_#atribuidos,e_#eventos,e_t_prom,c_advertiser,c_osmin,...,i_t_prom,i_t_max,i_app_id,i_#installs,i_model,i_language,i_type,i_wifi,i_implicit,segundos
0,41863526108385,0.126640,0.211054,0.126202,0.0,0.0,88.0,140062.647727,0.0,0.0,...,76472.0,76636.0,0.109299,4.0,0.006530,0.526228,0.834491,0.0,2.0,259200.0
1,161514654074162,0.057634,0.087007,0.058797,8.0,0.0,8.0,147937.250000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,152024.0
2,186034136943920,0.148482,0.253877,0.147929,0.0,0.0,13.0,60125.769231,0.0,0.0,...,60042.0,60042.0,0.063763,1.0,0.000000,0.000000,0.834491,0.0,1.0,259200.0
3,360710529886978,0.064439,0.016072,0.065793,0.0,0.0,3.0,214874.000000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
4,365882020742330,0.099017,0.019018,0.098669,0.0,0.0,57.0,151254.982456,0.0,0.0,...,96156.0,96156.0,0.014889,1.0,0.004079,0.526228,0.834491,0.0,0.0,259200.0

In [52]:
events = pd.read_csv('events_train_1921.csv')
clicks = pd.read_csv('clicks_train_1921.csv')
installs = pd.read_csv('installs_train_1921.csv')
target = pd.read_csv('installs_test_1921.csv')
todo = unir_archivos_sc(events,clicks,installs,target)
todo.to_csv('entrenar_sc_1921.csv', index=False)
todo.head()

,ref_hash,e_kind,e_app_id,e_event_id,e_#wifi,e_#atribuidos,e_#eventos,e_t_prom,c_advertiser,c_osmin,...,i_t_prom,i_t_max,i_app_id,i_#installs,i_model,i_language,i_type,i_wifi,i_implicit,segundos
0,40621409780134,0.005631,0.005478,0.005612,0.0,0.0,6.0,242807.833333,0.0,0.0,...,242267.0,242267.0,0.011750,1.0,0.006618,0.317287,0.833182,0.0,0.0,259200.0
1,41863526108385,0.147983,0.261183,0.147484,0.0,0.0,72.0,88923.736111,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
2,161514654074162,0.056457,0.083004,0.057539,8.0,0.0,8.0,61537.250000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,65624.0
3,360710529886978,0.070222,0.015924,0.071648,0.0,0.0,4.0,155603.000000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
4,365882020742330,0.099317,0.019578,0.098997,0.0,0.0,65.0,86141.076923,0.0,0.0,...,9756.0,9756.0,0.015855,1.0,0.003899,0.524056,0.833182,0.0,0.0,259200.0

In [53]:
events = pd.read_csv('events_train_2022.csv')
clicks = pd.read_csv('clicks_train_2022.csv')
installs = pd.read_csv('installs_train_2022.csv')
target = pd.read_csv('installs_test_2022.csv')
todo = unir_archivos_sc(events,clicks,installs,target)
todo.to_csv('entrenar_sc_2022.csv', index=False)
todo.head()

,ref_hash,e_kind,e_app_id,e_event_id,e_#wifi,e_#atribuidos,e_#eventos,e_t_prom,c_advertiser,c_osmin,...,i_t_prom,i_t_max,i_app_id,i_#installs,i_model,i_language,i_type,i_wifi,i_implicit,segundos
0,40621409780134,0.005677,0.005505,0.005659,0.0,0.0,6.0,156407.833333,0.0,0.0,...,155867.0,155867.0,0.012172,1.0,0.006409,0.324184,0.828972,0.0,0.0,259200.0
1,41863526108385,0.146337,0.262990,0.145857,0.0,0.0,51.0,31455.568627,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
2,161514654074162,0.091154,0.088657,0.091189,50.0,0.0,51.0,241464.294118,0.0,0.0,...,238424.0,238424.0,0.056471,1.0,0.007606,0.515034,0.828972,1.0,1.0,259200.0
3,168103949904656,0.090038,0.035244,0.091922,0.0,0.0,10.0,173599.100000,0.0,0.0,...,173373.0,173373.0,0.028381,1.0,0.000253,0.324184,0.828972,0.0,0.0,259200.0
4,186034136943920,0.133386,0.262990,0.132950,0.0,0.0,28.0,237222.571429,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0

In [54]:
events = pd.read_csv('events_train_2123.csv')
clicks = pd.read_csv('clicks_train_2123.csv')
installs = pd.read_csv('installs_train_2123.csv')
target = pd.read_csv('installs_test_2123.csv')
todo = unir_archivos_sc(events,clicks,installs,target)
todo.to_csv('entrenar_sc_2123.csv', index=False)
todo.head()

,ref_hash,e_kind,e_app_id,e_event_id,e_#wifi,e_#atribuidos,e_#eventos,e_t_prom,c_advertiser,c_osmin,...,i_t_prom,i_t_max,i_app_id,i_#installs,i_model,i_language,i_type,i_wifi,i_implicit,segundos
0,40621409780134,0.008657,0.005934,0.008633,0.0,0.0,9.0,122304.666667,0.0,0.0,...,69467.0,69467.0,0.012626,1.0,0.006177,0.328401,0.826917,0.0,0.0,259200.0
1,41863526108385,0.085450,0.264696,0.085150,0.0,0.0,8.0,9126.125000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
2,69039685746313,0.044512,0.028056,0.044368,4.0,0.0,4.0,235984.500000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
3,161514654074162,0.093511,0.083326,0.093581,56.0,0.0,58.0,165162.413793,0.0,0.0,...,152024.0,152024.0,0.049540,1.0,0.007135,0.510374,0.826917,1.0,1.0,259200.0
4,168103949904656,0.087588,0.034847,0.089625,0.0,0.0,10.0,87199.100000,0.0,0.0,...,86973.0,86973.0,0.028577,1.0,0.000251,0.328401,0.826917,0.0,0.0,259200.0

In [7]:
events = pd.read_csv('events_train_2426.csv')
clicks = pd.read_csv('clicks_train_2426.csv')
installs = pd.read_csv('installs_train_2426.csv')
target = pd.read_csv('ids.csv')
todo = unir_archivos_sc(events,clicks,installs,target)
todo.to_csv('predecir_sc_2426.csv', index=False)
todo.head()

,ref_hash,e_kind,e_app_id,e_event_id,e_#wifi,e_#atribuidos,e_#eventos,e_t_prom,c_advertiser,c_osmin,...,i_t_prom,i_t_max,i_app_id,i_#installs,i_model,i_language,i_type,i_wifi,i_implicit,segundos
0,41863526108385,0.135702,0.222804,0.135130,0.0,0.0,57.0,192838.719298,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
1,69039685746313,0.061761,0.029999,0.061509,13.0,0.0,16.0,229631.812500,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
2,90072729247980,0.048354,0.222804,0.048151,0.0,0.0,3.0,66661.000000,0.0,0.0,...,66650.0,66650.0,0.075728,1.0,0.001783,0.343916,0.823905,0.0,0.0,259200.0
3,161514654074162,0.084897,0.089999,0.087090,2.0,0.0,2.0,154222.500000,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0
4,168103949904656,0.084897,0.032703,0.087090,0.0,0.0,3.0,109329.666667,0.0,0.0,...,259200.0,259200.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,259200.0